os: linux
language: node_js

node_js:
  - 10

services:
  - docker

before_install:
  # Cloudfront edge lambdas support nodejs up to 10.x
  - docker pull mageops/aws-lambda-build:nodejs10.x
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

env:
  - LAMBDA_RUNTIME=nodejs-yarn

jobs:
  include:
    - stage: test
      script: yarn && yarn test && rm -rf node_modules

    - stage: build
      script: >
        docker run \
          --rm \
          --tty \
          --volume "$(pwd):/var/app" \
          mageops/aws-lambda-build:nodejs10.x $LAMBDA_RUNTIME edge-lambda-deploy-package

deploy:
  - provider: releases
    token: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: "*deploy-package*.zip"
    skip_cleanup: true
    cleanup: false
    on:
      tags: true