os: linux
language: generic

services:
  - docker

before_install:
  - docker pull mageops/aws-lambda-build

env:
  - LAMBDA_RUNTIME=nodejs-yarn

script: >
  docker run \
    --rm \
    --tty \
    --volume "$(pwd):/var/app" \
    mageops/aws-lambda-build $LAMBDA_RUNTIME edge-lambda-deploy-package

deploy:
  - provider: releases
    token: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: "*deploy-package*.zip"
    skip_cleanup: true
    cleanup: false
    on:
      tags: true